### ISSUE TITLE
Dynamic lightbox name

### ISSUE THREAD

**Issue by ppoetsma** [mendix/Lightbox#1]
Hi, I am evaluating your widget and it is nearly the perfect solution for my application. I need a dynamic part to the "lightbox name" property. I have a listview where in each iteration I show a group of images and each lightbox should show just that group of images. However currently it shows all images in all groups in that listview. Would it be possible to add a variable part to the lightbox name or eventually make it fully dynamic so I can create the groups?

I look forward to hear from you.

Regards,
Paul

**Comment by JelteMX** [comment]
Hi Paul,

Could you send us an e-mail to community [at] mendix.com, refer to this issue on Github and mention me? I'll see what we can do for you. Need to have a test-project to exactly figure out what you want to do.

**Comment by ppoetsma** [comment]
Thank you Jelte
