### ISSUE TITLE
Not compatible with Mendix v. 6+

### ISSUE THREAD

**Issue by bramvandijk** [mendix/Lightbox#2]

**Comment by JelteMX** [comment]
Can you please elaborate why not? We have tested all our widgets against MX6, Lightbox does not have any deprecations as far as I know.

**Comment by bramvandijk** [comment]
Hi Jelte,

I used Lightbox with Mendix version 6.2.1 and it works great when I’m running it in sandbox or local.
However when I tried to create a package to deploy in a test environment I got an error that my widgets were not compatible.
So, I went to the Mendix Modeler en tried Tools/Check Widgets and again an error emerged. From then on Lightbox stopped working, even locally.

Maybe that helps?

Cheers,

Bram

**Comment by JelteMX** [comment]
Hi Bram, thanks. I have noticed I did fix this issue in the past, BUT, I forgot to push these changes to Github. Can you check [this version](https://github.com/mendix/Lightbox/blob/master/test/widgets/Lightbox.mpk) for me? If this fixes it, I'll make sure it's updated in the AppStore a.s.a.p.

**Comment by bramvandijk** [comment]
Hi Jelte, I noticed this issue a while back, and I just remembered this morning to inform you here!
I worked around using Lightbox at the time, so at this moment I don't have a project with Lightbox in it. I can check it later though :)

**Comment by JelteMX** [comment]
Well I have checked again (my colleague mentioned the same problem) and it turns out to be an issue with uppercase vs lowercase names of folders. I made sure everything is lowercase now, which seems to fix the issue (check widgets now works, deployment issue is resolved)

Thanks for mentioning. I'll update it in the AppStore a.s.a.p.

**Comment by JelteMX** [comment]
[v2.3.0](https://github.com/mendix/Lightbox/releases/tag/v2.3.0) contains the update, will be updated in the AppStore soon

**Comment by bramvandijk** [comment]
Ah nice!
