### ISSUE TITLE
Widget does not refresh when image changes

### ISSUE THREAD

**Issue by ppoetsma** [mendix/Lightbox#3]
Hi,

Consider this use case:
1. A page that shows the image using the widget
2. Click on Edit to upload a new image (via popup)
3. After Save (Refresh UI is enabled) and closing the Edit page the widget does not show the new image
4. Click on the image and the widget shows the old image
5. Press CTRL-F5 in your browser and the page shows the new image

Can you make the widget refresh when the image (object or content) changes?

Regards,
Paul

**Comment by ppoetsma** [comment]
Hi Jelte,

Any chance this is solved soon? We are experiencing issues on production. When a user opens a page with the widget while there is no real image yet he sees a placeholder image (for example with an avatar where you by default see a placeholder). The page is closed, an image is added by another user/process and when the page is reopened the placeholder is still visible. Browser refresh does not work. Any other user who never had that object visible will see the right image right away.

If you do not have time on short notice, do you have a hint where to fix it?

Regards,
Paul

**Comment by ppoetsma** [comment]
Sorry, closed the issue; hit the wrong button :-(

**Comment by ppoetsma** [comment]
Hi Jelte,

I added a Date.now to the URL (two location in the Javascript) to generate unique URL's. The cause is browser caching and this prevents it.

"file?" + Date.now() + "&target=internal&guid="

Regards,
Paul

**Comment by JelteMX** [comment]
Fixed in [2.4.1](https://github.com/mendix/Lightbox/releases/tag/v2.4.1)
